### ISSUE TITLE
Unable to run this module in juliabox need help regarding this.

### ISSUE THREAD

**Issue by RAJ53AKKI** [bcbi/CTakesParser.jl#3]
Hi

Processed clinical text using CTAKES 4.0 and tried YTEX to store the information to DB. But not working correctly. Now I am trying to parse the xmi file using this module but unable to. I am using julia version 1.0.3 in juliabox.com. 
I am new to Julia.
Need more information to use this module.

Can you please help me regarding this.

any help will be appreciated.
Thanks in advance.

**Comment by mirestrepo** [comment]
@RAJ53AKKI we haven't updated this package to run in Julia 1.0 and above - updates should be coming in the next few weeks.

**Comment by mirestrepo** [comment]
@RAJ53AKKI I have updated the package to work on Julia 1.0 and above. Tests are passing - I'm going to close this issue. Feel free to re-open if you still run into issues
